### ISSUE TITLE
运行出现崩溃

### ISSUE THREAD

**Issue by wowo3129** [moon-sky/AndroidRecorder#1]
10-11 19:02:40.969 4857-4857/com.ai.moonvsky.androidrecorder E/AudioRecord: AudioFlinger could not create record track, status: -1
10-11 19:02:40.975 4857-4857/com.ai.moonvsky.androidrecorder E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
10-11 19:02:40.975 4857-4857/com.ai.moonvsky.androidrecorder E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
10-11 19:02:40.995 4857-4857/com.ai.moonvsky.androidrecorder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ai.moonvsky.androidrecorder, PID: 4857
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22641)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
        at android.view.View.performClick(View.java:5675) 
        at android.view.View$PerformClick.run(View.java:22641) 
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6251) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:982)
        at com.turing.biz.recoder.TuringRecorder.startRecord(TuringRecorder.java:106)
        at com.turing.biz.recoder.AudioRecordManager.startRecord(AudioRecordManager.java:29)
        at com.ai.moonvsky.androidrecorder.MainActivity.recorder(MainActivity.java:49)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
        at android.view.View.performClick(View.java:5675) 
        at android.view.View$PerformClick.run(View.java:22641) 
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6251) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by moon-sky** [comment]
系统版本是多少？是否打开相关录音权限？我这个版本暂时没有加动态权限获取
